allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  prisma: true
minimumReleaseAgeExclude:
  - nodemailer@7.0.7 || 7.0.11 || 8.0.4 || 8.0.5 || 8.0.8 || 8.0.9 || 9.0.1
  - tar@7.5.3 || 7.5.4 || 7.5.7 || 7.5.8 || 7.5.10 || 7.5.11 || 7.5.16 || 7.5.17 || 7.5.18 || 7.5.19 || 7.5.21
overrides:
  nodemailer@<7.0.7: ^7.0.7
  nodemailer@<8.0.4: ^8.0.4
  nodemailer@<=8.0.4: ^8.0.5
  nodemailer@<=8.0.7: ^8.0.8
  nodemailer@<=8.0.8: ^8.0.9
  nodemailer@<=9.0.0: ^9.0.1
  nodemailer@>=3.0.0 <=7.0.10: ^7.0.11
  tar@<7.5.7: ^7.5.7
  tar@<7.5.8: ^7.5.8
  tar@<=7.5.10: ^7.5.11
  tar@<=7.5.15: ^7.5.16
  tar@<=7.5.16: ^7.5.17
  tar@<=7.5.17: ^7.5.18
  tar@<=7.5.18: ^7.5.19
  tar@<=7.5.2: ^7.5.3
  tar@<=7.5.20: ^7.5.21
  tar@<=7.5.3: ^7.5.4
  tar@<=7.5.9: ^7.5.10
